# Generated by Django 5.1.3 on 2026-08-06 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('icon', models.CharField(default='💰', help_text='Emoji icon for the wallet', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_lent', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(blank=True, help_text='Expected return date', null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to='main.wallet')),
            ],
            options={
                'ordering': ['is_returned', '-date_lent'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('business', 'Business'), ('gift', 'Gift'), ('investment', 'Investment'), ('refund', 'Refund'), ('other', 'Other')], default='salary', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='main.wallet')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('food', 'Food & Groceries'), ('transport', 'Transport'), ('wifi', 'WiFi Bill'), ('internet', 'Internet'), ('mobile', 'Mobile Recharge'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('dress', 'Dress & Clothing'), ('health', 'Health & Medicine'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('donation', 'Donation'), ('other', 'Other')], default='food', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main.wallet')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_borrowed', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(blank=True, help_text='Expected return date', null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='main.wallet')),
            ],
            options={
                'ordering': ['is_returned', '-date_borrowed'],
            },
        ),
    ]
